
services:

    _defaults:
        autowire:   true

    ################################################################################
    # AutoWire for Controllers
    BadPixxel\Md2Pdf\Bundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    ################################################################################
    # Md2Pdf Services
    BadPixxel\Md2Pdf\Services\TwigRenderer: ~
    BadPixxel\Md2Pdf\Services\DomPdfBuilder: ~
